version: "3"

services:

  nginx:
    image: nginx:alpine
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynet
    depends_on:
      - app

  app:
    image: php:8.1-fpm-alpine
    build:
      dockerfile: ./app/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    networks:
      - mynet
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file # by default file will be save /var/lib/docker/containers
      options:
        max-size: '10m'
        max-file: '3'

networks:
  mynet:
    driver: overlay